name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Ejercicio 1
      id: ejercicio-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Ejercicio 1
        setup-command: ''
        command: php test/ejercicio1_test.php
        timeout: 10
        max-score: 1
    - name: Ejercicio 2
      id: ejercicio-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Ejercicio 2
        setup-command: ''
        command: php test/ejercicio2_test.php
        timeout: 10
        max-score: 1
    - name: Ejercicio 3
      id: ejercicio-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Ejercicio 3
        setup-command: ''
        command: php test/ejercicio3_test.php
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EJERCICIO-1_RESULTS: "${{steps.ejercicio-1.outputs.result}}"
        EJERCICIO-2_RESULTS: "${{steps.ejercicio-2.outputs.result}}"
        EJERCICIO-3_RESULTS: "${{steps.ejercicio-3.outputs.result}}"
      with:
        runners: ejercicio-1,ejercicio-2,ejercicio-3
